name: Insomnia configuration workflow template

on:
  workflow_call:
    inputs:
      OPEN_API_SPEC:
        required: true
        type: string

jobs:
  inso-lint:
    runs-on: self-hosted
    steps:
      - name: Lint OpenAPI specification
        run: inso lint spec ${{ inputs.OPEN_API_SPEC }}
  inso-generate-config:
    runs-on: self-hosted
    steps:
      - name: Generate decK config
        run: inso generate config ${{ inputs.OPEN_API_SPEC }} -t declarative